spring.application.name=uam

server.servlet.context-path=/uam

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

jwt.secret=${JWT_SECRET:Yf3Qq8d2mB9r7PpK4Xz0Lw1Mr6Vc8Nb5Hs2Jd9Rk3Tu8Wx4Cg7Zh1Qp6Ss9Et4Uv}
jwt.expiration=${JWT_EXPIRATION:3600000}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:63604/uam
spring.datasource.username=myuser
spring.datasource.password=mypassword

